version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: steganography-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OUTPUT_DIR=./output
      - GIN_MODE=release
    volumes:
      - backend_output:/root/output
    networks:
      - steganography-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: steganography-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - steganography-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    restart: unless-stopped

volumes:
  backend_output:
    driver: local

networks:
  steganography-network:
    driver: bridge
